[build]
    # Default build command.
    command = "echo 'default context'"

    # Directory with the serverless Lambda functions to deploy to AWS.
    functions = ".netlify/functions"

[dev]
    framework = "#static"
    functions = ".netlify/functions"